# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_share', '0002_auto_20170924_0140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='organizer',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
